import Link from 'next/link';

export default function Home() {
  return <main className="min-h-screen overflow-hidden bg-paper">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-7"><Link href="/" className="flex items-center gap-3 font-bold"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-forest text-xl text-mint">T</span><span className="tracking-tight">TESLA<span className="text-forest">POOL</span><small className="ml-2 font-normal text-slate-500">DHAKA</small></span></Link><Link href="/login" className="rounded-full border border-ink/15 px-5 py-2.5 text-sm font-semibold hover:bg-white">Sign in <span aria-hidden="true">↗</span></Link></header>
    <section className="mx-auto grid min-h-[75vh] max-w-7xl items-center gap-14 px-6 py-12 lg:grid-cols-[1.1fr_.9fr]">
      <div><p className="mb-6 inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-xs font-bold uppercase tracking-[.18em] text-forest"><span className="h-2 w-2 rounded-full bg-lime-500"/> Banani rush-hour pooling</p><h1 className="max-w-3xl text-6xl font-semibold leading-[.98] tracking-[-.06em] sm:text-7xl">Dhaka moves<br/><span className="text-forest">better together.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-600">Book a shared electric ride, split the fare in paisa-precise pricing, and make the daily commute a little lighter.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/login" className="rounded-full bg-forest px-7 py-4 text-sm font-bold text-white transition hover:bg-ink">Find my ride <span className="ml-6 text-mint">↗</span></Link><div className="rounded-full border border-ink/10 px-6 py-4 text-sm text-slate-600">Electric · Shared · Simple</div></div><div className="mt-12 flex gap-10 border-t border-ink/10 pt-6 text-sm"><div><b className="block text-2xl">3 seats</b><span className="text-slate-500">per Bullet vehicle</span></div><div><b className="block text-2xl">20%</b><span className="text-slate-500">pool fare discount</span></div><div><b className="block text-2xl">0</b><span className="text-slate-500">tailpipe emissions</span></div></div></div>
      <div className="relative mx-auto w-full max-w-lg"><div className="absolute -right-8 -top-8 h-52 w-52 rounded-full bg-mint/70 blur-3xl"/><div className="relative rounded-[2rem] bg-forest p-7 text-white shadow-card sm:p-9"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-mint">Your commute, reimagined</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Banani → the city</h2></div><span className="rounded-full bg-white/10 px-3 py-1 text-xs">LIVE ROUTES</span></div><div className="my-9 rounded-3xl bg-white p-5 text-ink"><div className="flex gap-4"><div className="flex flex-col items-center"><span className="h-3 w-3 rounded-full border-[3px] border-forest"/><span className="my-1 h-12 border-l border-dashed border-slate-300"/><span className="h-3 w-3 rounded-full bg-mint ring-2 ring-forest"/></div><div className="flex flex-1 flex-col justify-between"><div><small className="text-slate-400">PICKUP</small><p className="font-semibold">Banani, Dhaka</p></div><div><small className="text-slate-400">POPULAR DROP-OFFS</small><p className="font-semibold">Mohakhali · Gulshan 1</p></div></div></div></div><div className="flex items-center justify-between border-t border-white/15 pt-5"><div><p className="text-sm text-white/60">Meet your driver</p><p className="mt-1 font-semibold">Jashim <span className="ml-1 text-mint">· Bullet</span></p></div><div className="flex -space-x-2"><span className="grid h-9 w-9 place-items-center rounded-full border-2 border-forest bg-[#f7c8a7] text-xs font-bold text-ink">N</span><span className="grid h-9 w-9 place-items-center rounded-full border-2 border-forest bg-[#b8d8d0] text-xs font-bold text-ink">R</span><span className="grid h-9 w-9 place-items-center rounded-full border-2 border-forest bg-mint text-xs font-bold text-ink">+1</span></div></div></div><div className="absolute -bottom-7 -left-8 rounded-2xl bg-white px-5 py-4 shadow-card"><p className="text-xs text-slate-500">Example pooled fare</p><p className="mt-1 text-xl font-bold">৳96 <span className="text-sm font-medium text-slate-400">/ seat</span></p></div></div>
    </section><footer className="mx-auto max-w-7xl px-6 pb-7 text-xs text-slate-400">A better way across Banani. Built for people, powered by electric.</footer>
  </main>;
}
